### ISSUE TITLE
New driver support (version 516.40) - pattern not found

### ISSUE THREAD

**Issue by reloxx13** [keylase/nvidia-patch#544]
The pattern has changed again :( autopatcher fails 

```
nvidia-patch\win\tools\autopatch>python.exe autopatch.py 516.40
Downloading... ( https://international.download.nvidia.com/Windows/516.40/516.40-desktop-win10-win11-64bit-international-dch-whql.exe TO temp\516.40-desktop-win10-win11-64bit-international-dch-whql.exe )
This may take a while (~800MB)

7-Zip 20.00 alpha (x64) : Copyright (c) 1999-2020 Igor Pavlov : 2020-02-06

Scanning the drive for archives:
1 file, 822061184 bytes (784 MiB)

Extracting archive: temp\516.40-desktop-win10-win11-64bit-international-dch-whql.exe
--
Path = temp\516.40-desktop-win10-win11-64bit-international-dch-whql.exe
Type = PE
Physical Size = 822061184
CPU = x86
Characteristics = Executable 32-bit NoRelocs
Created = 2021-01-22 17:55:28
Headers Size = 1024
Checksum = 822076341
Name = PackageLauncher.exe
Image Size = 1019904
Section Alignment = 4096
File Alignment = 512
Code Size = 613376
Initialized Data Size = 377344
Uninitialized Data Size = 0
Linker Version = 9.0
OS Version = 5.0
Image Version = 0.0
Subsystem Version = 5.0
Subsystem = Windows GUI
DLL Characteristics = TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment =
{
FileVersion: 1.0.11.0
FileVersion: 1.0.11
ProductVersion: 1.0.11.0
ProductVersion: 1.0.11
CompanyName: NVIDIA Corporation
FileDescription: NVIDIA Package Launcher
InternalName: PackageLauncher
LegalCopyright: Copyright © 2011-2021 NVIDIA Corporation
OriginalFilename: PackageLauncher.exe
PrivateBuild: Jan 22, 2021
ProductName: NVIDIA Package Launcher
}
----
Path = [0]
Size = 821060560
Packed Size = 821060560
Virtual Size = 821060560
Offset = 991744
--
Path = [0]
Type = 7z
Offset = 709
Physical Size = 821059844
Tail Size = 7
Headers Size = 20323
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Files: 88
Size:       304175458
Compressed: 822061184
Traceback (most recent call last):
  File "autopatch.py", line 273, in <module>
    main()
  File "autopatch.py", line 269, in main
    patch_flow(*params, direct=args.direct, stdout=args.stdout)
  File "autopatch.py", line 212, in patch_flow
    patch = make_patch(installer_file,
  File "autopatch.py", line 162, in make_patch
    raise PatternNotFoundException("Pattern not found.")
__main__.PatternNotFoundException: Pattern not found.
```

**Comment by reloxx13** [comment]
would be kind if you can take a look @keylase

**Comment by jailuthra** [comment]
@reloxx13 can you test #547?

**Comment by reloxx13** [comment]
hey @jailuthra 

looks fine, thank you very much!

can you open the wiki for edit? i wanted to add the windows command for patch testing

ffmpeg download https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

```
ffmpeg.exe -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda ^
-f lavfi -i testsrc -t 50 ^
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 4M -f null - ^
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 1M -f null - ^
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 8M -f null - ^
-vf hwupload -c:a copy -c:v h264_nvenc -b:v 6M -f null -  
```

![grafik](https://user-images.githubusercontent.com/14855001/176503179-35690ed4-b94a-410a-92e9-a3c1dc41de08.png)

**Comment by jailuthra** [comment]
@reloxx13 i don’t have permission to open the wiki, i think only keylase does. but i’m able to edit so i’ll add it
